name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: javascript
          git-user: ${{ github.event.head_commit.author.username }}
          deployment-branch: gh-pages
